<?php

$associazioniGiocoAzienda = array(
    array("id_gioco" => 1, "id_azienda" => 1, "ruolo" => "sviluppatore"),
    array("id_gioco" => 1, "id_azienda" => 2, "ruolo" => "publisher"),
    array("id_gioco" => 2, "id_azienda" => 3, "ruolo" => "sviluppatore"),
    array("id_gioco" => 2, "id_azienda" => 3, "ruolo" => "publisher"),
    array("id_gioco" => 3, "id_azienda" => 4, "ruolo" => "sviluppatore"),
    array("id_gioco" => 3, "id_azienda" => 4, "ruolo" => "publisher"),
    array("id_gioco" => 4, "id_azienda" => 5, "ruolo" => "sviluppatore"),
    array("id_gioco" => 4, "id_azienda" => 5, "ruolo" => "publisher"),
    array("id_gioco" => 5, "id_azienda" => 6, "ruolo" => "sviluppatore"),
    array("id_gioco" => 5, "id_azienda" => 7, "ruolo" => "publisher"),
    array("id_gioco" => 6, "id_azienda" => 8, "ruolo" => "sviluppatore"),
    array("id_gioco" => 6, "id_azienda" => 8, "ruolo" => "publisher"),
    array("id_gioco" => 7, "id_azienda" => 1, "ruolo" => "sviluppatore"),
    array("id_gioco" => 7, "id_azienda" => 2, "ruolo" => "publisher"),
    array("id_gioco" => 8, "id_azienda" => 9, "ruolo" => "sviluppatore"),
    array("id_gioco" => 8, "id_azienda" => 9, "ruolo" => "publisher"),
    array("id_gioco" => 9, "id_azienda" => 10, "ruolo" => "sviluppatore"),
    array("id_gioco" => 9, "id_azienda" => 10, "ruolo" => "publisher"),
    array("id_gioco" => 10, "id_azienda" => 11, "ruolo" => "sviluppatore"),
    array("id_gioco" => 10, "id_azienda" => 11, "ruolo" => "publisher"),
    array("id_gioco" => 11, "id_azienda" => 1, "ruolo" => "sviluppatore"),
    array("id_gioco" => 12, "id_azienda" => 12, "ruolo" => "sviluppatore"),
    array("id_gioco" => 12, "id_azienda" => 13, "ruolo" => "publisher"),
    array("id_gioco" => 13, "id_azienda" => 1, "ruolo" => "sviluppatore"),
    array("id_gioco" => 13, "id_azienda" => 14, "ruolo" => "sviluppatore"),
    array("id_gioco" => 13, "id_azienda" => 15, "ruolo" => "publisher"),
    array("id_gioco" => 14, "id_azienda" => 9, "ruolo" => "sviluppatore"),
    array("id_gioco" => 14, "id_azienda" => 9, "ruolo" => "publisher"),
    array("id_gioco" => 15, "id_azienda" => 16, "ruolo" => "sviluppatore"),
    array("id_gioco" => 15, "id_azienda" => 16, "ruolo" => "publisher"),
    array("id_gioco" => 16, "id_azienda" => 17, "ruolo" => "sviluppatore"),
    array("id_gioco" => 16, "id_azienda" => 17, "ruolo" => "publisher"),
    array("id_gioco" => 17, "id_azienda" => 18, "ruolo" => "sviluppatore"),
    array("id_gioco" => 17, "id_azienda" => 18, "ruolo" => "publisher"),
    array("id_gioco" => 18, "id_azienda" => 19, "ruolo" => "sviluppatore"),
    array("id_gioco" => 18, "id_azienda" => 19, "ruolo" => "publisher"),
    array("id_gioco" => 19, "id_azienda" => 20, "ruolo" => "sviluppatore"),
    array("id_gioco" => 19, "id_azienda" => 20, "ruolo" => "publisher"),
    array("id_gioco" => 20, "id_azienda" => 21, "ruolo" => "sviluppatore"),
    array("id_gioco" => 20, "id_azienda" => 15, "ruolo" => "publisher"),
    array("id_gioco" => 21, "id_azienda" => 22, "ruolo" => "sviluppatore"),
    array("id_gioco" => 21, "id_azienda" => 15, "ruolo" => "publisher"),
    array("id_gioco" => 22, "id_azienda" => 23, "ruolo" => "sviluppatore"),
    array("id_gioco" => 22, "id_azienda" => 24, "ruolo" => "publisher"),
    array("id_gioco" => 23, "id_azienda" => 25, "ruolo" => "sviluppatore"),
    array("id_gioco" => 23, "id_azienda" => 25, "ruolo" => "publisher"),
    array("id_gioco" => 24, "id_azienda" => 26, "ruolo" => "sviluppatore"),
    array("id_gioco" => 24, "id_azienda" => 27, "ruolo" => "publisher"),
    array("id_gioco" => 25, "id_azienda" => 28, "ruolo" => "sviluppatore"),
    array("id_gioco" => 25, "id_azienda" => 24, "ruolo" => "publisher"),
    array("id_gioco" => 26, "id_azienda" => 9, "ruolo" => "sviluppatore"),
    array("id_gioco" => 26, "id_azienda" => 9, "ruolo" => "publisher")
);
?>
